### ISSUE TITLE
LBT warnings "accumulated time exceeds t_max" with jetscape_user.xml example

### ISSUE THREAD

**Issue by jdmulligan** [JETSCAPE/JETSCAPE#60] opened 2020-09-27 06:02 UTC
Reported by @kkauder:

The default `jescape_user.xml` with LBT goes into an infinite (or at least long) loop with an endless stream of
```
accumulated time exceeds t_max
15.6    0.2    0.4
accumulated time exceeds t_max
16.1    0.2    0.7
...
```

@shanshan-cao @amajumder can you please have a look how this can be fixed, or if some example setting in `jetscape_user.xml` should be updated?

**Comment by shanshan-cao** [comment] 2020-09-27 09:12
It's not a bug. Previously for mid-rapidity, we prepare LBT integral table till t = 14 fm, which should be sufficient. But if one runs the code for forward backward rapidity, the particle propagates for time longer than 14 fm and is still in the medium, then this warning message jumps out. We can extend the integral table later. The code will not be caught in an infinite loop.

**Comment by Hendrik1704** [comment] 2024-02-21 20:45
With the newest version of the LBT tables this issue does not occur anymore, I'll close it now.

**Closed by Hendrik1704** 2024-02-21 20:45 UTC
Labels: enhancement
